(definstances instances
    ([instancia1] of Obra
        (nombre "La Gioconda (Mona Lisa)")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1503)
        (estilo "Alta Renacimiento")
        (tematica "Retrato")
        (dimensiones "77 x 53")
        (sala 12)
        (relevancia 3))


    ([instancia2] of Obra
        (nombre "La Última Cena")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1498)
        (estilo "Alta Renacimiento")
        (tematica "Religiosa")
        (dimensiones "460 x 880")
        (sala 8)
        (relevancia 3))

    ([instancia3] of Obra
        (nombre "La Escuela de Atenas")
        (autor "Rafael Sanzio")
        (epoca "Renacimiento")
        (anio 1511)
        (estilo "Renacimiento Italiano")
        (tematica "Histórica")
        (dimensiones "500 x 770")
        (sala 14)
        (relevancia 3))


    ([instancia4] of Obra
        (nombre "El Nacimiento de Venus")
        (autor "Sandro Botticelli")
        (epoca "Renacimiento")
        (anio 1486)
        (estilo "Renacimiento Italiano")
        (tematica "Mitológica")
        (dimensiones "172.5 x 278.9")
        (sala 10)
        (relevancia 2))


    ([instancia5] of Obra
        (nombre "Las Meninas")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1656)
        (estilo "Escuela Española Barroca")
        (tematica "Retrato")
        (dimensiones "318 x 276")
        (sala 16)
        (relevancia 3))


    ([instancia6] of Obra
        (nombre "La Ronda de Noche")
        (autor "Rembrandt")
        (epoca "Barroco")
        (anio 1642)
        (estilo "Escuela Holandesa Barroca")
        (tematica "Histórica")
        (dimensiones "363 x 437")
        (sala 11)
        (relevancia 3))


    ([instancia7] of Obra
        (nombre "El Jardín de las Delicias")
        (autor "Hieronymus Bosch (El Bosco)")
        (epoca "Renacimiento")
        (anio 1515)
        (estilo "Renacimiento Nórdico")
        (tematica "Religiosa")
        (dimensiones "389 x 220")
        (sala 15)
        (relevancia 3))


    ([instancia8] of Obra
        (nombre "La Libertad Guiando al Pueblo")
        (autor "Eugène Delacroix")
        (epoca "Romanticismo")
        (anio 1830)
        (estilo "Romanticismo Francés")
        (tematica "Histórica")
        (dimensiones "260 x 325")
        (sala 20)
        (relevancia 3))


    ([instancia9] of Obra
        (nombre "Construcción Blanda con Judías Hervidas (Premonición de la Guerra Civil)")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1936)
        (estilo "Surrealismo Español")
        (tematica "Histórica")
        (dimensiones "100 x 99")
        (sala 40)
        (relevancia 3))


    ([instancia10] of Obra
        (nombre "Guernica")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1937)
        (estilo "Cubismo Español")
        (tematica "Histórica")
        (dimensiones "349 x 776")
        (sala 25)
        (relevancia 3))


    ([instancia11] of Obra
        (nombre "El Grito")
        (autor "Edvard Munch")
        (epoca "Expresionismo")
        (anio 1893)
        (estilo "Expresionismo Noruego")
        (tematica "Retrato")
        (dimensiones "91 x 73.5")
        (sala 18)
        (relevancia 3))


    ([instancia12] of Obra
        (nombre "El Beso")
        (autor "Gustav Klimt")
        (epoca "Simbolismo")
        (anio 1908)
        (estilo "Modernismo Vienés")
        (tematica "Retrato")
        (dimensiones "180 x 180")
        (sala 19)
        (relevancia 3))


    ([instancia13] of Obra
        (nombre "Impresión, Sol Naciente")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1872)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "48 x 63")
        (sala 22)
        (relevancia 3))


    ([instancia14] of Obra
        (nombre "Los Girasoles")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1888)
        (estilo "Postimpresionismo Holandés")
        (tematica "Naturaleza Muerta")
        (dimensiones "92 x 73")
        (sala 21)
        (relevancia 3))

    ([instancia15] of Obra
        (nombre "La Noche Estrellada")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1889)
        (estilo "Postimpresionismo Holandés")
        (tematica "Paisaje")
        (dimensiones "73.7 x 92.1")
        (sala 21)
        (relevancia 3))


    ([instancia16] of Obra
        (nombre "Cisnes que se Reflejan como Elefantes")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1937)
        (estilo "Surrealismo Español")
        (tematica "Abstracta")
        (dimensiones "51 x 77")
        (sala 40)
        (relevancia 3))


    ([instancia17] of Obra
        (nombre "Las Tres Gracias")
        (autor "Peter Paul Rubens")
        (epoca "Barroco")
        (anio 1639)
        (estilo "Barroco Flamenco")
        (tematica "Mitológica")
        (dimensiones "221 x 181")
        (sala 9)
        (relevancia 3))

    ([instancia18] of Obra
        (nombre "La Balsa de la Medusa")
        (autor "Théodore Géricault")
        (epoca "Romanticismo")
        (anio 1818)
        (estilo "Romanticismo Francés")
        (tematica "Histórica")
        (dimensiones "491 x 716")
        (sala 14)
        (relevancia 3))

    ([instancia19] of Obra
        (nombre "El Baile en el Moulin de la Galette")
        (autor "Pierre-Auguste Renoir")
        (epoca "Impresionismo")
        (anio 1876)
        (estilo "Impresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "131 x 175")
        (sala 17)
        (relevancia 3))

    ([instancia20] of Obra
        (nombre "Saturno devorando a su hijo")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1823)
        (estilo "Pintura Negra")
        (tematica "Mitológica")
        (dimensiones "143 x 81")
        (sala 6)
        (relevancia 3))

    ([instancia21] of Obra
        (nombre "El Caballero de la Mano en el Pecho")
        (autor "El Greco")
        (epoca "Renacimiento")
        (anio 1580)
        (estilo "Manierismo Español")
        (tematica "Retrato")
        (dimensiones "81 x 66")
        (sala 15)
        (relevancia 3))

    ([instancia22] of Obra
        (nombre "El Juramento de los Horacios")
        (autor "Jacques-Louis David")
        (epoca "Neoclasicismo")
        (anio 1784)
        (estilo "Neoclasicismo Francés")
        (tematica "Histórica")
        (dimensiones "330 x 425")
        (sala 12)
        (relevancia 3))

    ([instancia23] of Obra
        (nombre "La Muerte de Marat")
        (autor "Jacques-Louis David")
        (epoca "Neoclasicismo")
        (anio 1793)
        (estilo "Neoclasicismo Francés")
        (tematica "Histórica")
        (dimensiones "162 x 128")
        (sala 13)
        (relevancia 3))

    ([instancia24] of Obra
        (nombre "El Coloso")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1808)
        (estilo "Romanticismo Español")
        (tematica "Histórica")
        (dimensiones "116 x 105")
        (sala 10)
        (relevancia 3))

    ([instancia25] of Obra
        (nombre "La Venus del Espejo")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1651)
        (estilo "Barroco Español")
        (tematica "Mitológica")
        (dimensiones "123 x 177")
        (sala 16)
        (relevancia 3))

    ([instancia26] of Obra
        (nombre "La Fragua de Vulcano")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1630)
        (estilo "Barroco Español")
        (tematica "Mitológica")
        (dimensiones "223 x 290")
        (sala 18)
        (relevancia 3))

    ([instancia27] of Obra
        (nombre "Muchacha con un Pendiente de Perla")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1665)
        (estilo "Escuela Holandesa Barroca")
        (tematica "Retrato")
        (dimensiones "44.5 x 39")
        (sala 7)
        (relevancia 3))

    ([instancia28] of Obra
        (nombre "Vista de Delft")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1660)
        (estilo "Escuela Holandesa Barroca")
        (tematica "Paisaje")
        (dimensiones "96.5 x 115.7")
        (sala 13)
        (relevancia 3))

    ([instancia29] of Obra
        (nombre "La Primavera")
        (autor "Sandro Botticelli")
        (epoca "Renacimiento")
        (anio 1482)
        (estilo "Renacimiento Italiano")
        (tematica "Mitológica")
        (dimensiones "203 x 314")
        (sala 10)
        (relevancia 3))

    ([instancia30] of Obra
        (nombre "La Anunciación")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1472)
        (estilo "Renacimiento Italiano")
        (tematica "Religiosa")
        (dimensiones "98 x 217")
        (sala 9)
        (relevancia 2))

    ([instancia31] of Obra
        (nombre "El Rapto de Europa")
        (autor "Tiziano")
        (epoca "Renacimiento")
        (anio 1562)
        (estilo "Renacimiento Veneciano")
        (tematica "Mitológica")
        (dimensiones "185 x 205")
        (sala 15)
        (relevancia 3))

    ([instancia32] of Obra
        (nombre "El Jardín del Amor")
        (autor "Peter Paul Rubens")
        (epoca "Barroco")
        (anio 1633)
        (estilo "Barroco Flamenco")
        (tematica "Costumbrista")
        (dimensiones "198 x 283")
        (sala 20)
        (relevancia 3))

    ([instancia33] of Obra
        (nombre "La Tempestad")
        (autor "Giorgione")
        (epoca "Renacimiento")
        (anio 1508)
        (estilo "Renacimiento Veneciano")
        (tematica "Paisaje")
        (dimensiones "82 x 73")
        (sala 11)
        (relevancia 2))

    ([instancia34] of Obra
        (nombre "Judith decapitando a Holofernes")
        (autor "Artemisia Gentileschi")
        (epoca "Barroco")
        (anio 1620)
        (estilo "Barroco Italiano")
        (tematica "Histórica")
        (dimensiones "199 x 162")
        (sala 6)
        (relevancia 3))

    ([instancia35] of Obra
        (nombre "El Entierro del Conde de Orgaz")
        (autor "El Greco")
        (epoca "Renacimiento")
        (anio 1586)
        (estilo "Manierismo Español")
        (tematica "Religiosa")
        (dimensiones "480 x 360")
        (sala 17)
        (relevancia 3))

    ([instancia36] of Obra
        (nombre "Baile Campestre")
        (autor "Nicolas Poussin")
        (epoca "Barroco")
        (anio 1634)
        (estilo "Clasicismo Barroco")
        (tematica "Costumbrista")
        (dimensiones "114 x 180")
        (sala 8)
        (relevancia 2))

    ([instancia37] of Obra
        (nombre "Los Jugadores de Cartas")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1895)
        (estilo "Postimpresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "47 x 56")
        (sala 19)
        (relevancia 3))

    ([instancia38] of Obra
        (nombre "El Mercado de Esclavos")
        (autor "Jean-Léon Gérôme")
        (epoca "Academicismo")
        (anio 1866)
        (estilo "Academicismo Francés")
        (tematica "Histórica")
        (dimensiones "85 x 129")
        (sala 14)
        (relevancia 3))

    ([instancia39] of Obra
        (nombre "El Almuerzo de los Remeros")
        (autor "Pierre-Auguste Renoir")
        (epoca "Impresionismo")
        (anio 1881)
        (estilo "Impresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "129.5 x 172.7")
        (sala 21)
        (relevancia 3))

    ([instancia40] of Obra
        (nombre "Mujer con Sombrilla")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1875)
        (estilo "Impresionismo Francés")
        (tematica "Retrato")
        (dimensiones "100 x 81")
        (sala 22)
        (relevancia 3))

    ([instancia41] of Obra
        (nombre "El Violinista")
        (autor "Marc Chagall")
        (epoca "Expresionismo")
        (anio 1912)
        (estilo "Expresionismo Ruso")
        (tematica "Retrato")
        (dimensiones "77 x 98")
        (sala 29)
        (relevancia 1))

    ([instancia42] of Obra
        (nombre "La Ola")
        (autor "Gustave Courbet")
        (epoca "Realismo")
        (anio 1870)
        (estilo "Realismo Francés")
        (tematica "Paisaje")
        (dimensiones "88 x 112")
        (sala 24)
        (relevancia 1))

    ([instancia43] of Obra
        (nombre "Campesinos Comiendo Sopa")
        (autor "Jean-François Millet")
        (epoca "Realismo")
        (anio 1850)
        (estilo "Realismo Francés")
        (tematica "Costumbrista")
        (dimensiones "74 x 60")
        (sala 18)
        (relevancia 1))

    ([instancia44] of Obra
        (nombre "Joven con una Flor")
        (autor "Mary Cassatt")
        (epoca "Impresionismo")
        (anio 1880)
        (estilo "Impresionismo Americano")
        (tematica "Retrato")
        (dimensiones "92 x 73")
        (sala 25)
        (relevancia 1))

    ([instancia45] of Obra
        (nombre "Tarde en el Lago")
        (autor "Gustave Caillebotte")
        (epoca "Impresionismo")
        (anio 1876)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "54 x 65")
        (sala 22)
        (relevancia 1))

    ([instancia46] of Obra
        (nombre "La Encajera")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1669)
        (estilo "Escuela Holandesa Barroca")
        (tematica "Costumbrista")
        (dimensiones "24.5 x 21")
        (sala 9)
        (relevancia 1))

    ([instancia47] of Obra
        (nombre "Mujer con Mandolina")
        (autor "Georges Braque")
        (epoca "Cubismo")
        (anio 1910)
        (estilo "Cubismo Francés")
        (tematica "Retrato")
        (dimensiones "92 x 73")
        (sala 28)
        (relevancia 1))

    ([instancia48] of Obra
        (nombre "Tarde de Domingo")
        (autor "Camille Pissarro")
        (epoca "Impresionismo")
        (anio 1895)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "60 x 80")
        (sala 20)
        (relevancia 1))

    ([instancia49] of Obra
        (nombre "Amapolas")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1873)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "50 x 65")
        (sala 21)
        (relevancia 1))

    ([instancia50] of Obra
        (nombre "Maternidad")
        (autor "Suzanne Valadon")
        (epoca "Postimpresionismo")
        (anio 1899)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "89 x 116")
        (sala 26)
        (relevancia 1))

    ([instancia51] of Obra
        (nombre "La Lectura")
        (autor "Henri Fantin-Latour")
        (epoca "Realismo")
        (anio 1870)
        (estilo "Realismo Francés")
        (tematica "Retrato")
        (dimensiones "77 x 92")
        (sala 17)
        (relevancia 1))

    ([instancia52] of Obra
        (nombre "Niña con Cesta de Frutas")
        (autor "Berthe Morisot")
        (epoca "Impresionismo")
        (anio 1885)
        (estilo "Impresionismo Francés")
        (tematica "Retrato")
        (dimensiones "65 x 81")
        (sala 23)
        (relevancia 1))

    ([instancia53] of Obra
        (nombre "Barcos en el Puerto")
        (autor "Alfred Sisley")
        (epoca "Impresionismo")
        (anio 1876)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "60 x 80")
        (sala 22)
        (relevancia 1))

    ([instancia54] of Obra
        (nombre "Catedral de Rouen")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1894)
        (estilo "Impresionismo Francés")
        (tematica "Religiosa")
        (dimensiones "100 x 65")
        (sala 24)
        (relevancia 1))

    ([instancia55] of Obra
        (nombre "Niña con Pez Dorado")
        (autor "Pierre Bonnard")
        (epoca "Postimpresionismo")
        (anio 1910)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "81 x 100")
        (sala 27)
        (relevancia 1))

    ([instancia56] of Obra
        (nombre "Paisaje con Árboles")
        (autor "Camille Corot")
        (epoca "Realismo")
        (anio 1855)
        (estilo "Realismo Francés")
        (tematica "Paisaje")
        (dimensiones "72 x 92")
        (sala 19)
        (relevancia 1))

    ([instancia57] of Obra
        (nombre "Dos Mujeres Caminando")
        (autor "Camille Pissarro")
        (epoca "Impresionismo")
        (anio 1873)
        (estilo "Impresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "46 x 55")
        (sala 20)
        (relevancia 1))

    ([instancia58] of Obra
        (nombre "El Estanque de Nenúfares")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1899)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "100 x 81")
        (sala 21)
        (relevancia 1))

    ([instancia59] of Obra
        (nombre "El Desayuno")
        (autor "Édouard Manet")
        (epoca "Realismo")
        (anio 1868)
        (estilo "Realismo Francés")
        (tematica "Costumbrista")
        (dimensiones "80 x 100")
        (sala 18)
        (relevancia 1))

    ([instancia60] of Obra
        (nombre "Retrato de una Mujer con Sombrero")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1895)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "55 x 46")
        (sala 26)
        (relevancia 1))

    ([instancia61] of Obra
        (nombre "La Barca de Dante")
        (autor "Eugène Delacroix")
        (epoca "Romanticismo")
        (anio 1822)
        (estilo "Romanticismo Francés")
        (tematica "Histórica")
        (dimensiones "189 x 241")
        (sala 14)
        (relevancia 2))

    ([instancia62] of Obra
        (nombre "El Descubrimiento de América por Cristóbal Colón")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1959)
        (estilo "Surrealismo Místico")
        (tematica "Histórica")
        (dimensiones "410 x 284")
        (sala 40)
        (relevancia 2))

    ([instancia63] of Obra
        (nombre "Campesina con Sombrero")
        (autor "Paul Gauguin")
        (epoca "Postimpresionismo")
        (anio 1894)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "65 x 75")
        (sala 27)
        (relevancia 1))

    ([instancia64] of Obra
        (nombre "Retrato de la Madre del Artista")
        (autor "James McNeill Whistler")
        (epoca "Realismo")
        (anio 1871)
        (estilo "Realismo Americano")
        (tematica "Retrato")
        (dimensiones "144.3 x 162.4")
        (sala 19)
        (relevancia 2))

    ([instancia65] of Obra
        (nombre "La Danza")
        (autor "Henri Matisse")
        (epoca "Fauvismo")
        (anio 1910)
        (estilo "Fauvismo Francés")
        (tematica "Costumbrista")
        (dimensiones "260 x 391")
        (sala 28)
        (relevancia 3))

    ([instancia66] of Obra
        (nombre "El Hilo Rojo")
        (autor "Joan Miró")
        (epoca "Surrealismo")
        (anio 1927)
        (estilo "Surrealismo Español")
        (tematica "Abstracta")
        (dimensiones "73 x 92")
        (sala 29)
        (relevancia 1))

    ([instancia67] of Obra
        (nombre "La Balsa de la Medusa")
        (autor "Théodore Géricault")
        (epoca "Romanticismo")
        (anio 1818)
        (estilo "Romanticismo Francés")
        (tematica "Histórica")
        (dimensiones "491 x 716")
        (sala 12)
        (relevancia 3))

    ([instancia68] of Obra
        (nombre "Casa junto al Lago")
        (autor "Wassily Kandinsky")
        (epoca "Expresionismo")
        (anio 1908)
        (estilo "Expresionismo Alemán")
        (tematica "Paisaje")
        (dimensiones "80 x 120")
        (sala 25)
        (relevancia 2))

    ([instancia69] of Obra
        (nombre "El Bebedor de Absenta")
        (autor "Édouard Manet")
        (epoca "Realismo")
        (anio 1858)
        (estilo "Realismo Francés")
        (tematica "Retrato")
        (dimensiones "180 x 105")
        (sala 18)
        (relevancia 1))

    ([instancia70] of Obra
        (nombre "Los Girasoles")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1888)
        (estilo "Postimpresionismo Holandés")
        (tematica "Naturaleza muerta")
        (dimensiones "92.1 x 73")
        (sala 27)
        (relevancia 3))

    ([instancia71] of Obra
        (nombre "El Estudio del Artista")
        (autor "Gustave Courbet")
        (epoca "Realismo")
        (anio 1855)
        (estilo "Realismo Francés")
        (tematica "Costumbrista")
        (dimensiones "361 x 598")
        (sala 24)
        (relevancia 2))

    ([instancia72] of Obra
        (nombre "Naturaleza Muerta con Manzanas")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1890)
        (estilo "Postimpresionismo Francés")
        (tematica "Naturaleza muerta")
        (dimensiones "65 x 80")
        (sala 26)
        (relevancia 1))

    ([instancia73] of Obra
        (nombre "Impresión, Sol Naciente")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1872)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "48 x 63")
        (sala 22)
        (relevancia 3))

    ([instancia74] of Obra
        (nombre "El Adivino")
        (autor "Georges de La Tour")
        (epoca "Barroco")
        (anio 1630)
        (estilo "Barroco Francés")
        (tematica "Costumbrista")
        (dimensiones "101 x 123")
        (sala 16)
        (relevancia 2))

    ([instancia75] of Obra
        (nombre "El Puente de Argenteuil")
        (autor "Claude Monet")
        (epoca "Impresionismo")
        (anio 1874)
        (estilo "Impresionismo Francés")
        (tematica "Paisaje")
        (dimensiones "60 x 80")
        (sala 21)
        (relevancia 1))

    ([instancia76] of Obra
        (nombre "Retrato de Vincent van Gogh")
        (autor "Henri de Toulouse-Lautrec")
        (epoca "Postimpresionismo")
        (anio 1887)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "54 x 66")
        (sala 26)
        (relevancia 2))

    ([instancia77] of Obra
        (nombre "La Persistencia de la Memoria")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1931)
        (estilo "Surrealismo Español")
        (tematica "Abstracta")
        (dimensiones "24 x 33")
        (sala 30)
        (relevancia 3))

    ([instancia78] of Obra
        (nombre "El Café Nocturno")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1888)
        (estilo "Postimpresionismo Holandés")
        (tematica "Costumbrista")
        (dimensiones "72 x 92")
        (sala 27)
        (relevancia 2))

    ([instancia79] of Obra
        (nombre "Paisaje Alpino")
        (autor "Caspar David Friedrich")
        (epoca "Romanticismo")
        (anio 1824)
        (estilo "Romanticismo Alemán")
        (tematica "Paisaje")
        (dimensiones "70 x 90")
        (sala 13)
        (relevancia 1))

    ([instancia80] of Obra
        (nombre "La Noche Estrellada")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1889)
        (estilo "Postimpresionismo Holandés")
        (tematica "Paisaje")
        (dimensiones "73.7 x 92.1")
        (sala 28)
        (relevancia 3))

    ([instancia81] of Obra
        (nombre "La Cosecha")
        (autor "Pieter Bruegel el Viejo")
        (epoca "Renacimiento")
        (anio 1565)
        (estilo "Renacimiento Flamenco")
        (tematica "Costumbrista")
        (dimensiones "118 x 160")
        (sala 8)
        (relevancia 2))

    ([instancia82] of Obra
        (nombre "La Lección de Anatomía del Dr. Nicolaes Tulp")
        (autor "Rembrandt")
        (epoca "Barroco")
        (anio 1632)
        (estilo "Escuela Barroca Holandesa")
        (tematica "Histórica")
        (dimensiones "216 x 169")
        (sala 10)
        (relevancia 3))

    ([instancia83] of Obra
        (nombre "Naturaleza Muerta con Botella de Vino")
        (autor "Juan Gris")
        (epoca "Cubismo")
        (anio 1915)
        (estilo "Cubismo Español")
        (tematica "Naturaleza muerta")
        (dimensiones "60 x 81")
        (sala 28)
        (relevancia 1))

    ([instancia84] of Obra
        (nombre "La Inmaculada Concepción")
        (autor "Bartolomé Esteban Murillo")
        (epoca "Barroco")
        (anio 1678)
        (estilo "Barroco Español")
        (tematica "Religiosa")
        (dimensiones "267 x 190")
        (sala 15)
        (relevancia 2))

    ([instancia85] of Obra
        (nombre "Naturaleza Muerta con Silla de Rejilla")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1912)
        (estilo "Cubismo Sintético")
        (tematica "Naturaleza muerta")
        (dimensiones "29 x 37")
        (sala 30)
        (relevancia 2))

    ([instancia86] of Obra
        (nombre "La Vista de Toledo")
        (autor "El Greco")
        (epoca "Manierismo")
        (anio 1596)
        (estilo "Manierismo Español")
        (tematica "Paisaje")
        (dimensiones "121 x 108")
        (sala 11)
        (relevancia 2))

    ([instancia87] of Obra
        (nombre "El Viñedo Rojo")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1888)
        (estilo "Postimpresionismo Holandés")
        (tematica "Paisaje")
        (dimensiones "75 x 93")
        (sala 27)
        (relevancia 3))

    ([instancia88] of Obra
        (nombre "La Virgen de las Rocas")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1486)
        (estilo "Renacimiento Italiano")
        (tematica "Religiosa")
        (dimensiones "199 x 122")
        (sala 5)
        (relevancia 3))

    ([instancia89] of Obra
        (nombre "Paisaje con Cascada")
        (autor "Jacob van Ruisdael")
        (epoca "Barroco")
        (anio 1660)
        (estilo "Barroco Holandés")
        (tematica "Paisaje")
        (dimensiones "98 x 128")
        (sala 9)
        (relevancia 1))

    ([instancia90] of Obra
        (nombre "El Matrimonio Arnolfini")
        (autor "Jan van Eyck")
        (epoca "Renacimiento")
        (anio 1434)
        (estilo "Renacimiento Flamenco")
        (tematica "Retrato")
        (dimensiones "82 x 60")
        (sala 6)
        (relevancia 3))

    ([instancia91] of Obra
        (nombre "El Barco Fantasma")
        (autor "Joseph Mallord William Turner")
        (epoca "Romanticismo")
        (anio 1842)
        (estilo "Romanticismo Inglés")
        (tematica "Paisaje")
        (dimensiones "91 x 122")
        (sala 13)
        (relevancia 2))

    ([instancia92] of Obra
        (nombre "Hombre con un Sombrero")
        (autor "Amedeo Modigliani")
        (epoca "Expresionismo")
        (anio 1917)
        (estilo "Expresionismo Italiano")
        (tematica "Retrato")
        (dimensiones "100 x 65")
        (sala 29)
        (relevancia 1))

    ([instancia93] of Obra
        (nombre "Los Jugadores de Cartas")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1894)
        (estilo "Postimpresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "60 x 73")
        (sala 26)
        (relevancia 3))

    ([instancia94] of Obra
        (nombre "El Juramento de los Horacios")
        (autor "Jacques-Louis David")
        (epoca "Neoclasicismo")
        (anio 1784)
        (estilo "Neoclasicismo Francés")
        (tematica "Histórica")
        (dimensiones "330 x 425")
        (sala 17)
        (relevancia 2))

    ([instancia95] of Obra
        (nombre "La Despedida")
        (autor "Édouard Vuillard")
        (epoca "Postimpresionismo")
        (anio 1899)
        (estilo "Postimpresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "88 x 111")
        (sala 25)
        (relevancia 1))

    ([instancia96] of Obra
        (nombre "Retrato de Madame X")
        (autor "John Singer Sargent")
        (epoca "Realismo")
        (anio 1884)
        (estilo "Realismo Americano")
        (tematica "Retrato")
        (dimensiones "234 x 109")
        (sala 19)
        (relevancia 2))

    ([instancia97] of Obra
        (nombre "Las Espigadoras")
        (autor "Jean-François Millet")
        (epoca "Realismo")
        (anio 1857)
        (estilo "Realismo Francés")
        (tematica "Costumbrista")
        (dimensiones "83.5 x 111")
        (sala 18)
        (relevancia 3))

    ([instancia98] of Obra
        (nombre "El Carro de Heno")
        (autor "John Constable")
        (epoca "Romanticismo")
        (anio 1821)
        (estilo "Romanticismo Inglés")
        (tematica "Paisaje")
        (dimensiones "130 x 183")
        (sala 13)
        (relevancia 2))

    ([instancia99] of Obra
        (nombre "Bodegón con Manzanas")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1890)
        (estilo "Postimpresionismo Francés")
        (tematica "Naturaleza muerta")
        (dimensiones "65 x 81")
        (sala 26)
        (relevancia 1))

    ([instancia100] of Obra
        (nombre "La Tentación de San Antonio")
        (autor "Hieronymus Bosch (El Bosco)")
        (epoca "Renacimiento")
        (anio 1500)
        (estilo "Renacimiento Flamenco")
        (tematica "Religiosa")
        (dimensiones "131 x 119")
        (sala 7)
        (relevancia 3))

    ([instancia101] of Obra
        (nombre "La Belleza de Tahití")
        (autor "Paul Gauguin")
        (epoca "Postimpresionismo")
        (anio 1892)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "92 x 73")
        (sala 27)
        (relevancia 2))

    ([instancia102] of Obra
        (nombre "Retrato de Dora Maar")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1937)
        (estilo "Cubismo Español")
        (tematica "Retrato")
        (dimensiones "92 x 65")
        (sala 30)
        (relevancia 3))

    ([instancia103] of Obra
        (nombre "El Pífano")
        (autor "Édouard Manet")
        (epoca "Impresionismo")
        (anio 1866)
        (estilo "Impresionismo Francés")
        (tematica "Retrato")
        (dimensiones "160 x 97")
        (sala 22)
        (relevancia 1))

    ([instancia104] of Obra
        (nombre "El Molino de la Galette")
        (autor "Pierre-Auguste Renoir")
        (epoca "Impresionismo")
        (anio 1876)
        (estilo "Impresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "131 x 175")
        (sala 22)
        (relevancia 3))

    ([instancia105] of Obra
        (nombre "La Ninfa y el Sátiro")
        (autor "William-Adolphe Bouguereau")
        (epoca "Academicismo")
        (anio 1873)
        (estilo "Academicismo Francés")
        (tematica "Mitológica")
        (dimensiones "260 x 180")
        (sala 20)
        (relevancia 2))

    ([instancia106] of Obra
        (nombre "Mujer Leyendo una Carta")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1663)
        (estilo "Barroco Holandés")
        (tematica "Costumbrista")
        (dimensiones "46 x 39")
        (sala 9)
        (relevancia 3))

    ([instancia107] of Obra
        (nombre "Retrato de Giovanna Tornabuoni")
        (autor "Domenico Ghirlandaio")
        (epoca "Renacimiento")
        (anio 1488)
        (estilo "Renacimiento Italiano")
        (tematica "Retrato")
        (dimensiones "77 x 49")
        (sala 5)
        (relevancia 2))

    ([instancia108] of Obra
        (nombre "Muchacha con Aro")
        (autor "Pierre-Auguste Renoir")
        (epoca "Impresionismo")
        (anio 1885)
        (estilo "Impresionismo Francés")
        (tematica "Retrato")
        (dimensiones "116 x 81")
        (sala 22)
        (relevancia 1))

    ([instancia109] of Obra
        (nombre "La Casa Amarilla")
        (autor "Vincent van Gogh")
        (epoca "Postimpresionismo")
        (anio 1888)
        (estilo "Postimpresionismo Holandés")
        (tematica "Paisaje")
        (dimensiones "76 x 94")
        (sala 27)
        (relevancia 3))

    ([instancia110] of Obra
        (nombre "La Tempestad")
        (autor "Giorgione")
        (epoca "Renacimiento")
        (anio 1508)
        (estilo "Renacimiento Italiano")
        (tematica "Paisaje")
        (dimensiones "82 x 73")
        (sala 6)
        (relevancia 2))

    ([instancia111] of Obra
        (nombre "El Caballero de la Mano en el Pecho")
        (autor "El Greco")
        (epoca "Manierismo")
        (anio 1580)
        (estilo "Manierismo Español")
        (tematica "Retrato")
        (dimensiones "81 x 66")
        (sala 11)
        (relevancia 3))

    ([instancia112] of Obra
        (nombre "Le Moulin Rouge")
        (autor "Henri de Toulouse-Lautrec")
        (epoca "Postimpresionismo")
        (anio 1891)
        (estilo "Postimpresionismo Francés")
        (tematica "Costumbrista")
        (dimensiones "120 x 170")
        (sala 26)
        (relevancia 2))

    ([instancia113] of Obra
        (nombre "Madame Cézanne en la Silla Roja")
        (autor "Paul Cézanne")
        (epoca "Postimpresionismo")
        (anio 1877)
        (estilo "Postimpresionismo Francés")
        (tematica "Retrato")
        (dimensiones "81 x 65")
        (sala 26)
        (relevancia 1))

    ([instancia114] of Obra
        (nombre "La Masacre de los Inocentes")
        (autor "Peter Paul Rubens")
        (epoca "Barroco")
        (anio 1611)
        (estilo "Barroco Flamenco")
        (tematica "Histórica")
        (dimensiones "142 x 182")
        (sala 12)
        (relevancia 3))

    ([instancia115] of Obra
        (nombre "Retrato de una Mujer Desconocida")
        (autor "Ivan Kramskoi")
        (epoca "Realismo")
        (anio 1883)
        (estilo "Realismo Ruso")
        (tematica "Retrato")
        (dimensiones "75 x 99")
        (sala 18)
        (relevancia 2))

    ([instancia116] of Obra
        (nombre "La Rendición de Breda")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1635)
        (estilo "Barroco Español")
        (tematica "Histórica")
        (dimensiones "307 x 367")
        (sala 15)
        (relevancia 3))

    ([instancia117] of Obra
        (nombre "El Árbol de la Vida")
        (autor "Gustav Klimt")
        (epoca "Modernismo")
        (anio 1909)
        (estilo "Modernismo Austriaco")
        (tematica "Abstracta")
        (dimensiones "138 x 102")
        (sala 25)
        (relevancia 2))

    ([instancia118] of Obra
        (nombre "La Habitación Roja")
        (autor "Henri Matisse")
        (epoca "Fauvismo")
        (anio 1908)
        (estilo "Fauvismo Francés")
        (tematica "Costumbrista")
        (dimensiones "180 x 220")
        (sala 28)
        (relevancia 1))

    ([instancia119] of Obra
        (nombre "El Pintor en su Estudio")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1668)
        (estilo "Barroco Holandés")
        (tematica "Costumbrista")
        (dimensiones "120 x 100")
        (sala 10)
        (relevancia 3))

    ([instancia120] of Obra
        (nombre "La Encajera")
        (autor "Johannes Vermeer")
        (epoca "Barroco")
        (anio 1669)
        (estilo "Barroco Holandés")
        (tematica "Costumbrista")
        (dimensiones "24 x 21")
        (sala 10)
        (relevancia 2))

    ([instancia121] of Obra
        (nombre "El Quitasol")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1777)
        (estilo "Romanticismo Español")
        (tematica "Costumbrista")
        (dimensiones "104 x 152")
        (sala 14)
        (relevancia 2))

    ([instancia122] of Obra
        (nombre "El Tres de Mayo de 1808")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1814)
        (estilo "Romanticismo Español")
        (tematica "Histórica")
        (dimensiones "266 x 345")
        (sala 14)
        (relevancia 3))

    ([instancia123] of Obra
        (nombre "La Maja Desnuda")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1797)
        (estilo "Romanticismo Español")
        (tematica "Retrato")
        (dimensiones "97 x 190")
        (sala 14)
        (relevancia 3))

    ([instancia124] of Obra
        (nombre "La Familia de Carlos IV")
        (autor "Francisco de Goya")
        (epoca "Romanticismo")
        (anio 1801)
        (estilo "Romanticismo Español")
        (tematica "Retrato")
        (dimensiones "280 x 336")
        (sala 14)
        (relevancia 3))

    ([instancia125] of Obra
        (nombre "Mujer con Sombrero y Collar de Flores")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1939)
        (estilo "Cubismo Español")
        (tematica "Retrato")
        (dimensiones "61 x 50")
        (sala 30)
        (relevancia 2))

    ([instancia126] of Obra
        (nombre "Los Tres Músicos")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1921)
        (estilo "Cubismo Sintético")
        (tematica "Costumbrista")
        (dimensiones "204 x 188")
        (sala 30)
        (relevancia 3))

    ([instancia127] of Obra
        (nombre "La Mujer Llorando")
        (autor "Pablo Picasso")
        (epoca "Cubismo")
        (anio 1937)
        (estilo "Cubismo Español")
        (tematica "Retrato")
        (dimensiones "60 x 49")
        (sala 30)
        (relevancia 3))

    ([instancia128] of Obra
        (nombre "El Sueño")
        (autor "Pablo Picasso")
        (epoca "Surrealismo")
        (anio 1932)
        (estilo "Surrealismo Español")
        (tematica "Retrato")
        (dimensiones "130 x 97")
        (sala 30)
        (relevancia 2))

    ([instancia129] of Obra
        (nombre "El Aguador de Sevilla")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1620)
        (estilo "Barroco Español")
        (tematica "Costumbrista")
        (dimensiones "105 x 80")
        (sala 15)
        (relevancia 2))

    ([instancia130] of Obra
        (nombre "Cristo Crucificado")
        (autor "Diego Velázquez")
        (epoca "Barroco")
        (anio 1632)
        (estilo "Barroco Español")
        (tematica "Religiosa")
        (dimensiones "249 x 170")
        (sala 15)
        (relevancia 3))

    ([instancia131] of Obra
        (nombre "El Hombre de Vitruvio")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1490)
        (estilo "Renacimiento Italiano")
        (tematica "Retrato")
        (dimensiones "34 x 25")
        (sala 3)
        (relevancia 3))

    ([instancia132] of Obra
        (nombre "Adoración de los Magos")
        (autor "Leonardo da Vinci")
        (epoca "Renacimiento")
        (anio 1481)
        (estilo "Renacimiento Italiano")
        (tematica "Religiosa")
        (dimensiones "246 x 243")
        (sala 3)
        (relevancia 3))

    ([instancia133] of Obra
        (nombre "El Gran Masturbador")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1929)
        (estilo "Surrealismo Español")
        (tematica "Abstracta")
        (dimensiones "110 x 150")
        (sala 40)
        (relevancia 3))

    ([instancia134] of Obra
        (nombre "Sueño Causado por el Vuelo de una Abeja Alrededor de una Granada un Segundo Antes de Despertar")
        (autor "Salvador Dalí")
        (epoca "Surrealismo")
        (anio 1944)
        (estilo "Surrealismo Español")
        (tematica "Abstracta")
        (dimensiones "51 x 41")
        (sala 40)
        (relevancia 3))
)







